### ISSUE TITLE
quartzplugin.so not found

### ISSUE THREAD

**Issue by mlhetland** [jheinen/GR.jl#7] opened 2015-07-28 12:59 UTC
When I use GR (with Julia 0.4) I get:
```
GKS: dlopen(/usr/local/gr/lib/quartzplugin.so, 1): image not found
```
Things (e.g., writing to a PDF file) still work, though.

**Comment by jheinen** [comment] 2015-07-28 13:25
Could you please run the following script and show the output:

    function testpath()
        if "GRDIR" in keys(ENV)
            grdir = ENV["GRDIR"]
        else
            grdir = joinpath(homedir(), "gr")
            if !isdir(grdir)
                grdir = "/usr/local/gr"
                if !isdir(grdir)
                    grdir = joinpath(Pkg.dir(), "GR", "deps", "gr")
                    if isdir(grdir)
                        ENV["GRDIR"] = grdir
                        ENV["GKS_FONTPATH"] = grdir
                    end
                end
            end
        end
        if contains(grdir, "site-packages")
            const libGR = joinpath(grdir, "libGR.so")
            ENV["GKS_FONTPATH"] = grdir
        elseif OS_NAME != :Windows
            const libGR = joinpath(grdir, "lib", "libGR.so")
        else
            const libGR = joinpath(grdir, "libGR.dll")
        end
        if !isfile(libGR)
            println("Unable to load GR framework runtime environment")
            exit(-1)
        end
        libGR3 = replace(libGR, "libGR", "libGR3")
        println(libGR)
        println(libGR3)
        for file in readdir(joinpath(grdir, "lib"))
            println(file)
        end
    end
    
    testpath()

Thanks.

**Comment by mlhetland** [comment] 2015-07-28 14:06
I'm not currently at the same machine, but now I tried installing and running it on another (OS X, Homebrew, Julia 0.4), and got a different error:

```
ERROR: LoadError: error compiling beginprint: could not load library "/Users/mlh/.julia/v0.4/GR/deps/gr/lib/libGR.so"
dlopen(/Users/mlh/.julia/v0.4/GR/deps/gr/lib/libGR.so, 1): Library not loaded: /opt/X11/lib/libXft.2.dylib
  Referenced from: /Users/mlh/.julia/v0.4/GR/deps/gr/lib/libGR.so
  Reason: image not found
 in include at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in include_from_node1 at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in process_options at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
 in _start at /usr/local/Cellar/julia/HEAD/lib/julia/sys.dylib
while loading /Users/mlh/[...], in expression starting on line 7
```

My `libXft` is at `/usr/X11/lib/libXft.2.dylib`…

For this machine, the output of your script is:

```
/Users/mlh/.julia/v0.4/GR/deps/gr/lib/libGR.so
/Users/mlh/.julia/v0.4/GR/deps/gr/lib/libGR3.so
figplugin.so
glplugin.so
gsplugin.so
gtkplugin.so
htmplugin.so
libGKS.so
libGR.so
libGR3.so
movplugin.so
pgfplugin.so
qtplugin.so
quartzplugin.so
svgplugin.so
wmfplugin.so
wxplugin.so
zmqplugin.so
```

… buut I guess this is sort of a different issue :-)

I'll run the script on the other machine when I get back to it.

**Comment by jheinen** [comment] 2015-07-28 14:35
On OS X, the GR framework requires [XQuartz](http://xquartz.macosforge.org/) to be installed. May be I should provide an (extra) version built without X11 support in the future. These are the deps right now:

    /usr/local/GR/lib/libGR.so:
        /usr/local/gr/lib/libGR.so (compatibility version 0.0.0, current version 0.0.0)
        /opt/X11/lib/libfreetype.6.dylib (compatibility version 18.0.0, current version 18.2.0)
        /usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
        /opt/X11/lib/libXft.2.dylib (compatibility version 6.0.0, current version 6.2.0)
        /opt/X11/lib/libfontconfig.1.dylib (compatibility version 10.0.0, current version 10.0.0)
        /opt/X11/lib/libXt.6.dylib (compatibility version 7.0.0, current version 7.0.0)
        /opt/X11/lib/libX11.6.dylib (compatibility version 10.0.0, current version 10.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)

**Comment by mlhetland** [comment] 2015-07-29 10:45
Hmright.

Well, anyway, here's the output from the original machine (the one where this issue originated):

```
/Users/mlh/.julia/v0.4/GR/deps/gr/lib/libGR.so
/Users/mlh/.julia/v0.4/GR/deps/gr/lib/libGR3.so
figplugin.so
glplugin.so
gsplugin.so
gtkplugin.so
htmplugin.so
libGKS.so
libGR.so
libGR3.so
movplugin.so
pgfplugin.so
qtplugin.so
quartzplugin.so
svgplugin.so
wmfplugin.so
wxplugin.so
zmqplugin.so
```

**Comment by jheinen** [comment] 2015-07-29 13:25
What is the output of the following console (Terminal) command?

    otool -L /Users/mlh/.julia/v0.4/GR/deps/gr/lib/quartzplugin.so

**Comment by mlhetland** [comment] 2015-07-30 09:14
```
/Users/mlh/.julia/v0.4/GR/deps/gr/lib/quartzplugin.so:
	quartzplugin.so (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 833.25.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 41.0.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1138.51.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 635.21.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 53.0.0)
```

**Comment by jheinen** [comment] 2015-07-30 09:30
The original message was:

    GKS: dlopen(/usr/local/gr/lib/quartzplugin.so, 1): image not found

So the question is, do you probably have the environment ``GRDIR`` set (to ``/usr/local/gr``) or is there a directory ``/usr/local/gr``? Either remove the environment and/or the directory ``/usr/local/gr``.

**Comment by mlhetland** [comment] 2015-07-31 11:00
Hm. I have neither, actually.

**Comment by jheinen** [comment] 2015-07-31 11:48
Could you (as a root user) please try to make the following link? (just temporary, for testing)

    ln -s /Users/mlh/.julia/v0.4/GR/deps/gr /usr/local/gr

**Comment by jheinen** [comment] 2015-07-31 20:03
I could reproduce the problem on a *fresh* OS X system. Please set the loader path previous before starting Julia (v4). In your case:

    export DYLD_LIBRARY_PATH=/Users/mlh/.julia/v0.4/GR/deps/gr/lib
    julia
    ...

If this works, I will fix the bug and provide a new GR version ASAP.
Sorry for the problems ...

**Comment by mlhetland** [comment] 2015-08-01 08:08
Yeah, that worked (i.e., setting `DYLD_LIBRARY_PATH`). However, GR now opened GKSTerm, which is not needed, given that I'm writing to a PDF. I guess that's also what forced the attempted load of `quartzplugin.so`, perhaps? Or maybe not. Either way, there's no need to launch interactive stuff when just writing to a file, I'd think – and I'd certainly prefer to avoid it.

**Comment by jheinen** [comment] 2015-08-01 08:31
I changed the binary (for OS X), so re-installing GR from scratch should work:

    ~ % julia
                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "help()" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.3.11 (2015-07-27 06:18 UTC)
     _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
    |__/                   |  x86_64-apple-darwin13.4.0
    
    julia> Pkg.add("GR")
    INFO: Initializing package repository /Users/jheinen/.julia/v0.3
    INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
    INFO: Cloning cache of GR from git://github.com/jheinen/GR.jl.git
    INFO: Installing GR v0.9.10
    INFO: Building GR
    INFO: Downloading pre-compiled GR 0.14.1 binary
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 21.8M  100 21.8M    0     0  93.8M      0 --:--:-- --:--:-- --:--:-- 93.5M
    INFO: Package database updated
    
    julia> import GR
    
    julia> GR.axes(0.1,0.1,0,0,2,2,0.01)
    
    julia> 

To avoid starting a terminal, you may set the output device before importing GR, e.g.

    julia> ENV["GKS_WSTYPE"]="pdf"
    "pdf"
    julia> import GR
    julia> GR.axes(0.1,0.1,0,0,2,2,0.01)

This will create a file ``gks.pdf`` in the current directory. I'll think about a better solution ...

**Comment by mlhetland** [comment] 2015-08-03 09:21
Well, I'm using 0.4 – not sure if that matters. But it didn't seem to help much:
```
$ julia
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+6313 (2015-07-28 11:48 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit 53aabc0* (5 days old master)
|__/                   |  x86_64-apple-darwin14.4.0

julia> Pkg.rm("GR")
...
julia> Pkg.update()
...
julia> Pkg.add("GR")
...
julia> import GR

julia> GR.axes(0.1,0.1,0,0,2,2,0.01)
GKS: dlopen(/usr/local/gr/lib/quartzplugin.so, 1): image not found
```

**Comment by jheinen** [comment] 2015-08-03 09:39
... there are probably some 'cached" files, because there is no information message about the download in your log:

    INFO: Downloading pre-compiled GR 0.14.1 binary

Pls try to (manually) remove ``/Users/mlh/.julia/v0.4/.cache/GR` ...

**Comment by mlhetland** [comment] 2015-08-03 09:49
OK, I did. It seems `Pkg` is pointing to the wrong thing, though…
```
julia> Pkg.add("GR")
INFO: Cloning cache of GR from git://github.com/jheinen/GR.jl.git
INFO: Installing GR v0.9.10
INFO: Building GR
INFO: Package database updated
```
Needless to say (since I'm getting an old version, somehow) the problem is still there.

**Comment by jheinen** [comment] 2015-08-04 06:32
... I tagged a new version - once, the PR is merged by the Julia maintainers (this afternoon?), the correct binary should be installed ,,,

**Comment by mlhetland** [comment] 2015-08-19 07:31
Works perfectly now!

**Closed** 2015-08-19 07:31 UTC
