### ISSUE TITLE
Consistent LaTeX support using the gr() backend to Plots

### ISSUE THREAD

**Issue by jlperla** [jheinen/GR.jl#93] opened 2018-02-01 18:42 UTC
This may be related to https://github.com/jheinen/GR.jl/issues/43 but I am posting a separate issue since we are interested in the use from the `gr` backend to `Plots.jl`.  I am doing most of these tests on juliabox.com, because that is what my students are using.

@jheinen : @sglyon and I have been trying to get a consistent solution for latex labels, titles, etc. that works in `Plots.jl` while swapping out backends.  There seems to be an inconsistency between the `gr` backend and the others.  The basic issue seems to be that GR automatically tex-ifies strings, where the others do not.  Also, GR seems to generate intermediate files for the latex in some cases, and not in others.

To see this, here is some example code. Tested on juliabox.
```julia
using Plots, LaTeXStrings

#pyplot backend with escaped string, no problem.
pyplot()
plot(rand(3); label="\$ \\alpha \$")

#gr with escaped string
gr()
# plot(rand(3); label="\$ \\alpha \$") #Using the same thing will fail.
#But the following works:
plot(rand(3); label="\\alpha") #i.e. remove the $ and GR automagically tex-ifies the strings...
```
As for the failure when escaping the string, on juliabox calling `plot(rand(3); label="\$ \\alpha \$")` says
```
sh: 1: dvipng: not found
dvipng: PNG conversion failed"
```
And on my desktop it works, but looks pretty hideous (and very different from the `plot(rand(3); label="\\alpha")`.  

Now, if we use the `LaTeXStrings.jl` package, then things seem pretty consistent with this.  The following works great with `pyplot`:
```julia
pyplot()
plot(rand(3); label=L"\alpha")
```
while 
```julia
gr()
plot(rand(3); label=L"\alpha")
```
either fails with the dvipng error on juliabox, or looks hideous on my local computer.

**Comment by jlperla** [comment] 2018-02-01 18:50
If I may guess what is happening: If GR sees latex-like backslashes in the text fields (without any $ escaping) then it automatically texifies the embedded code.  If it sees the $ escapes, then it runs latex to generate a png file and uses the image as the label/title (which looks pretty awful, or doesn't work if things are setup wrong).  The behavior with the LaTeXStrings is consistent with this, because LaTeXStrings automatically adds escaping $ around strings, i.e. `L"\alpha"`.s == "\$\alpha\$"`

So here is a suggestion:  Are you able write versions of the label, title, etc. which support `LaTeXStrings.LaTeXString` directly?  If so, you could take those strings and automatically strip out the $ around the string?  If you could, then it might just automatically use your existing display code, and wouldn't be a breaking change for anyone not combining LaTeXString and the gr backend?

I guess what I don't know is in the `Plots.jl` interface to your backend whether it is possible to get passed the `LaTeXString` directly or not.

Another option: just strip out the $ around the strings that come in for labels from Plots.jl.  I have yet to see a case where having the $ is better.

**Comment by jlperla** [comment] 2018-02-01 19:04
Sorry, just noticed in the https://github.com/jheinen/GR.jl/blob/master/src/GR.jl source about the mini-latex implemented in GR, which would explain the difference between the escaped and non-escaped text.  That said, I still stand by my recommendation that the $ $ support is not very useful (unless I am missing a usecase) because it either doesn't work, or looks terrible when it does.

**Comment by jlperla** [comment] 2018-02-07 17:59
Just to be clear on the issue here, it is less about making sure latex "works" and more about it not breaking things.  Right now if you put in a label like `"\$\\alpha\$"` it will either not show up at all, or be extremely ugly (depending on the setup as it seems to use a local latex setup).   This is very confusing for users who copy/paste code and I have never seen it useful.  Turning off the automatic running of latex by default (and stripping out any $ $ on the outside of a string to the internal GR mini-latex worked) would do a lot to help usability.

**Comment by mobius-eng** [comment] 2018-03-31 09:01
I guess it is connected to this one, one issue I ran into using GR with Plots in Juno:

This works fine:

```julia
using Plots
using LaTeXStrings
gr()

plot(sin, -2pi, 2pi, lab=L"\alpha")
```

But it breaks if I use other LaTeX symbols, like `\partial` or `\sin`: the plot is still displayed, but the label is missing and

```
\sin <...> : undefined symbol
```
is printed in the console.

**Comment by mobius-eng** [comment] 2018-04-08 20:01
I guess, it's Plots.jl issue then.

**Comment by jessebett** [comment] 2018-04-10 23:11
I also have this with the gr() backend.

`label = L"p\(x|\theta\)"` has its label missing.

'label = L"$p\(x|\theta\)$ rest of string"' shows the correct latex but with the `$` still shown.

**Comment by jheinen** [comment] 2018-04-11 06:01
I'm not a LaTeX expert, but I think you mean `L"p(x|\theta)"`

**Comment by jessebett** [comment] 2018-04-11 18:47
You're referring to the escapes for the parentheses? I tried it your way initially and the parenthesis disappeared, so I assumed they were needed by LaTeXStrings, but perhaps that's also a bug here.

**Comment by jlperla** [comment] 2018-06-10 20:50
I know this is closed, but I don't think it has really been fixed.  If part of this is in Plots.jl, it would be great to be able to track down where the problem might be.

**Comment by jheinen** [comment] 2018-06-11 06:05
```
using GR
mathtex(0.5,0.5,"p\\(x|\\theta\\)")
```

leads to `latex: failed to create a dvi file`

**Comment by jheinen** [comment] 2018-06-11 09:56
This issue should be fixed in https://github.com/jheinen/gr/commits/master. Pls checkout GR master and rebuild GR to download the latest run-time:
```
Pkg.checkout("GR")
ENV["GRDIR"]=""
Pkg.build("GR")
```

**Comment by jlperla** [comment] 2018-06-11 19:22
I tried it and it seems to be working well.  Can't test on juliabox (of course) but much better on my desktop.

The "pixelation" of the latex output is still somewhat of an issue, but I think that is a broader problem that isn't necessarily the fault of `GR`.

**Comment by jheinen** [comment] 2018-06-11 19:40
LaTeX formulas are created using 'dvipng' and rendered using a output-device dependent resolution. For display devices, a low resolution is used. I can probably add a flag to use a higher resolution for such devices, too.

**Comment by jlperla** [comment] 2018-06-11 19:41
That would be great. I can test it if you do. Most screens are so high resolution these days that it is noticeable

**Comment by mikolajpp** [comment] 2018-09-05 12:56
Definitely. With GR the LaTeX labels unfortunately look ugly in Jupyter notebooks, to the point it sticks out from the rest of the plot

**Comment by jheinen** [comment] 2018-09-05 13:04
Are you using the latest runtome? 0.33.0

**Comment by mikolajpp** [comment] 2018-09-05 13:42
Yes, running on 0.33.1 here. 
Here is what I see in jupyter: http://tinyimg.io/i/17VH0FE.png
It is very much visible on laptop screen

**Comment by jheinen** [comment] 2018-09-05 14:35
As a workaround you could force PNG output within Jupyter. For GR: inline(”PNG”), for Plots sth like gr(fmt=”PNG”) - not sure about the latter. If the results are ok for you, I can implement similar behavior in SVG ...

**Comment by mikolajpp** [comment] 2018-09-05 14:55
I used 
```
gr(fmt="png")
```
Now the quality of the entire plot, not just labels, is 2x as worse as label quality before, including messed up fonts

**Comment by jheinen** [comment] 2018-09-05 15:09
I can‘t test right now - but there must be sth totally wrong with the Plots GR backend. In GR it works. Maybe gr(”cairopng”) gives better results, I will test it tomorrow ...

**Comment by jheinen** [comment] 2018-09-06 15:27
The problem is fixed in GR master, but it requires an additional change in Plots, as the DPI settings in the GKS SVG driver had to be changed to create higher resolution LaTeX text.
![screenshot 2018-09-06 at 17 20 45](https://user-images.githubusercontent.com/5718244/45167734-0ba36c80-b1fa-11e8-8a18-2828fe308fc0.png)

**Comment by jheinen** [comment] 2018-09-06 15:30
Right now, you have to manually specify the correct DPI setting (in `Plots`):
```julia
using Plots
gr(dpi=400)
...
```
Will tag a new release soon ...

**Comment by Nosferican** [comment] 2018-10-22 16:19
Was this resolved?

**Comment by jheinen** [comment] 2018-10-23 06:59
I hope https://github.com/JuliaPlots/Plots.jl/pull/1800 will finally fix those problems.

**Comment by jleman** [comment] 2019-01-05 19:58
I am having a problem with plot label formatting in GR that seems to relate to this thread.  The code is:

`using GR
using LaTeXStrings

xlabel("Time Step")
ylabel("(E_{Z}[50])(V/m)")
plot(t,ez50, title=L"\sin x")`

The result is:

![image](https://user-images.githubusercontent.com/44458380/50728569-da23aa80-10e0-11e9-8ae2-2960372c8cbc.png)

I updated GR this morning though I got this same error with previous versions.  I am using Jupyter and Julia 1.0.3

Also, what is the escape sequence to show parentheses?  I reviewed the gr.textext documentation, but could not find it.  I am trying to get the vertical axis label to look like this:

![image](https://user-images.githubusercontent.com/44458380/50728587-2969db00-10e1-11e9-9934-a696ce85d380.png)

Thanks.

**Comment by jheinen** [comment] 2019-01-07 08:21
You need `dvipng` to use LaTeX style text output in GR. On RedHat, the required package is `texlive-dvipng`:
```
yum install texlive-dvipng
```

**Comment by korsbo** [comment] 2019-01-24 19:51
I had the same issue on Ubuntu and it was solved by:
```bash
sudo apt-get install dvipng
```

**Comment by damonturney** [comment] 2019-04-22 16:09
I'm using a Mac OS 10.14.2 Mojave with Atom Juno Julia, and I've installed MacTeX with dvipng installed, and I already did 

Pkg.update("GR")
ENV["GRDIR"]=""
Pkg.build("GR")

and I'm still getting this error:

using GR
mathtex(0.5,0.5,"p\\(x|\\theta\\)")
'sh: latex: command not found
latex: failed to create a dvi file'

and also this fails too
using Plots
using LaTeXStrings
plot(1,ylabel=L"")
'sh: latex: command not found
latex: failed to create a dvi file'

What's this error from?

**Comment by jheinen** [comment] 2019-04-22 19:43
It seems that `latex` and `dvipng` are not in your path. For TeXlive, the `PATH` variable should contain something like `/usr/local/TeX/bin/x86_64-darwin`.

**Comment by damonturney** [comment] 2019-04-22 20:42
Thank you -- you're correct.  I just needed to restart my Atom after the install of latex and dvipng.

**Closed** 2019-04-23 06:17 UTC

**Comment by Moelf** [comment] 2020-06-04 05:54
sorry to reply to a old thread, but what if I don't have access to the machine (cluster node), can a binary (`_jll`)be packed into GR or (Plots.jl) to solve this
