### ISSUE TITLE
[BUG] QtTerm non-square window size

### ISSUE THREAD

**Issue by gustaphe** [jheinen/GR.jl#385] opened 2021-04-07 16:19 UTC
I don't know if this is specific to my system (i3wm on Arch linux).

No matter the dimensions of the plot, GR reserves a square area for it in the window. This means that if the window is resized the figure is sometimes needlessly scaled down. This figure, for instance, could easily fill the window better but since it's trying to fit a square viewport it leaves a lot of empty space:

![image](https://user-images.githubusercontent.com/6677110/113898623-53cd0600-97cc-11eb-98b5-3f7352c35fc4.png)

Here's the same problem for a call `using Plots;gr();plot(randn(10,10); title="hi", size=(300,600))`:

![image](https://user-images.githubusercontent.com/6677110/113899062-b7573380-97cc-11eb-9df0-f135be09a5d9.png)

Is this a limitation in QtTerm, a bug or a specific issue with i3?

**Comment by mkitti** [comment] 2021-04-12 14:08
I just wanted to link the associated Discourse thread: https://discourse.julialang.org/t/chasing-a-gr-bug-non-square-figures/58819

In particular, quoting maintainer @jheinen 
> I can’t reproduce it on any of my desktop machines. I think it’s a problem with tiling window managers.

It would be good to know if this is the case?

**Comment by lieskjur** [comment] 2022-02-01 18:56
I am experiencing very similar behavior on LeftWM (tiling window).

**Comment by IngoMeyer441** [comment] 2022-02-02 07:21
Could you please send a full example which is broken? I would try to reproduce the issue.

**Comment by lieskjur** [comment] 2022-02-02 07:45
Most simple example I could come up with
```
using Plots
x = 1:10;
y = rand(10);
plot(x,y)
```
![image](https://user-images.githubusercontent.com/61360439/152112723-cc437942-5a01-4723-9ea2-be2e52443ce2.png)
![image](https://user-images.githubusercontent.com/61360439/152112793-6bd307fa-dc36-46c3-aa55-a149d54c886f.png)

Running on:
Distro: Manjaro Linux
WM: leftwm 1:0.2.11-1
Term: alacritty-ligatures 0.8.0.1772.g3ed0430-1
julia 2:1.7.1-4
Plots v1.25.2

**Comment by IngoMeyer441** [comment] 2022-02-02 11:26
@lieskjur Thanks for the details! I will try to reproduce this in a virtual machine.

**Comment by lieskjur** [comment] 2022-02-04 16:00
@IngoMeyer441 you are welcome. Glad I can help in some way.

**Comment by IngoMeyer441** [comment] 2022-02-15 11:09
This issue should be fixed in commit [6901a057](https://github.com/sciapp/gr/commit/6901a057bc32e4af9c9adad8e6710b99f80a24e2) (latest development version) of GR. I have run tests on Manjaro with LeftWM. The easiest way to use the patched version on Manjaro (or other Arch derivates) is:

1. Install the GR development version from the AUR:
    ```bash
    yay -S gr-framework-git
    ```
2. Rebuild Julia GR and use the installed GR package: In the Julia REPL:
    ```julia
    ENV["JULIA_GR_PROVIDER"] = "GR"
    import Pkg; Pkg.build("GR")
    ```

**Comment by IngoMeyer441** [comment] 2022-02-15 11:17
@mkitti Yes, this bug only occurs with tiling window managers. The problem was caused by a piece of code in gksqt which relied on the order of initial resize and paint events. Under floating window managers, there is an initial resize event followed by the first paint event. Under tiling window managers there are two resize events (for the initial size and for fitting the tile) and afterwards, the first paint event is invoked. The caused the `wswindow` in GR to be set to the default value (for a square painting area).

**Comment by gustaphe** [comment] 2022-02-15 12:14
Works perfectly on i3wm too. Thank you so much!

**Comment by lieskjur** [comment] 2022-02-19 11:34
Thank you very much.

**Closed** 2022-04-27 14:23 UTC
