### ISSUE TITLE
Inconsistent corner shape of line plots

### ISSUE THREAD

**Issue by shg** [jheinen/GR.jl#380] opened 2021-03-24 03:36 UTC
Small value difference causes visually very different results. It seems that GR switches how it render corners between so-called "bevel" join and "miter" join types according to the values. This is problematic because it introduces inconsistent correspondence between the impression from the graph and actual value variation. Is this behavior controllable with any attribute?

As far as I checked, the issue doesn't exists in PyPlot backend because it seems it always use "round" join type.

```julia
using Plots
gr()

default(thickness_scaling = 2)
plot(ylims = (0, 3), xlims = (-1, 7), legend = false)

for x0 = 0:1:3
    x = 2x0:0.1:2x0+0.2
    y = [1.53 + 0.01x0, 2.0, 1.0]
    plot!(x, y, line = 5, linecolor = "brown")
    plot!(x, y, line = 1, linecolor = "yellow")
end

savefig("plot_corner_shape.png")
```
![plot_corner_shape](https://user-images.githubusercontent.com/55463/112250325-80e1ca80-8c9c-11eb-93d4-72b672911e4d.png)

**Comment by jheinen** [comment] 2021-03-24 09:07
This behavior is probably specific to the Quartz plugin (GKSTerm). The effect does not occur in the GKS QtTerm. The current API does not provide functions for changing line join or cap attributes. It is used only at the driver level, and only for GDPs. The current API does not provide for changing line join/line cap attributes. It is used only at driver level, and only for GDPs. Since this functionality would have to be implemented in all GKS output drivers, the effort is significant. However, it is definitely on my radar.

**Comment by jheinen** [comment] 2021-03-24 09:11
BTW: In MPL (PyPlot) the problem does not occur because under macOS the CoreGraphics API (Quartz) is no longer used.

**Comment by shg** [comment] 2021-03-25 01:00
Thank you @jheinen for explanation. I found this issue when I was plotting a time-series data. In some situations, this can cause very unexpected results. Glad to hear you are looking at this.

```julia
n = 32
x = (1:n) .+ 0.1 * randn(n)
y = iseven.(1:n) * 4 .+ 2

plot(thickness_scaling = 2, left_margin = -5mm, bottom_margin = -5mm, legend = false)
plot!(x, y, line = 5, ylims = (0, 8))
plot!(x, y, line = 1, linecolor = "yellow")

savefig("plot_dummy_ts.png")
```

![plot_dummy_ts](https://user-images.githubusercontent.com/55463/112396219-1d5ea800-8d43-11eb-8b9c-f007d4f08fc5.png)

**Comment by shg** [comment] 2021-03-25 03:27
I personally think to make it always use round join is a reasonable choice. Round join is suitable for data visualization purpose because actual data points are always at the same distance from the line's outer edge. There might be some people who want to choose the current behavior for compatibility though.

**Comment by ChasingZenith** [comment] 2021-04-04 04:30
Please see This issue JuliaPlots/Plots.jl#3360.
I think that Miter join gives some strange behavior for some graphs.

**Comment by jheinen** [comment] 2021-04-06 08:46
I will fix that with the next release.

**Comment by ChasingZenith** [comment] 2021-04-08 23:18
Sorry for being not clear about my situation. I am a Linux user, not a macOS user. I find a new release is made and I find the problem is not fixed for me. Please see the issue here JuliaPlots/Plots.jl#3360 where I give several samples comparing the output of Miter join and others.

A short summary is here:

1. Miter join seems to cause some glitch when the line plot oscillates a lot. ( I am not quite sure since I am not an expert on CG)
2. When `savefig` with png, svg, pdf format, unexpected glitches become apparent.
3. The smoothness of the curve: (> means more smooth)
Round join > bavel join > Miter join with parameter 0 > Miter join with parameter 4 (GR's default setting)
4. Plots.jl Pyplot backend uses Miter join because GR does.
5. Python matplotlib use Round join.

Is there a special reason for preferring `Miter join` in GR?

BTW: should I make a new issue? I post it here because this issue also mentions miter join.

**Comment by jheinen** [comment] 2021-04-09 02:14
Ok, I probably was unclear. The latest patch releases were bug fixes for several problems related to the change to BinaryBuilder as the default provider for run-time libraries. This had highest priority for us.

I will change to line join behaviour ASAP and let you know about it. Please understand that GR contains several different output devices which all have to be changed, tested and profiled. That's why I can't just do it JIT.

I totally agree with you and will change the preferences where possible (without affecting drawing speed).

I hope I can provide a solution until the middle of the next week.

**Comment by jheinen** [comment] 2021-04-14 12:22
Right now I don't understand where the problem "starts". Could you please try the following example:
```julia
using GR

setwsviewport(0, 0.2, 0, 0.15)
setwswindow(0, 1, 0, 0.75)

setwindow(-1, 35, 0, 8)
setviewport(0.05, 0.95, 0.02, 0.73)

n = 32
x = (1:n) .+ 0.1 * randn(n)
y = iseven.(1:n) * 4 .+ 2

setlinewidth(10)
setlinecolorind(4)
polyline(x, y)
setlinewidth(2)
setlinecolorind(6)
polyline(x, y)
updatews()
```

**Comment by shg** [comment] 2021-04-14 22:28
In my environment, I got the this from the code.

<img width="1016" alt="gr_380_01" src="https://user-images.githubusercontent.com/55463/114787947-8faf2f00-9dbb-11eb-8e8a-516a457f3fa0.png">

With a slight modification (4 -> 3 in the line for calculating y) I get this. Because the angles get larger than the above plot and some reach the threshold.

<img width="1016" alt="gr_380_02" src="https://user-images.githubusercontent.com/55463/114787953-95a51000-9dbb-11eb-806f-36140e5731ad.png">

**Comment by ChasingZenith** [comment] 2021-05-30 11:30
> I will change to line join behaviour ASAP and let you know about it. Please understand that GR contains several different output devices which all have to be changed, tested and profiled. That's why I can't just do it JIT.
> 
> I totally agree with you and will change the preferences where possible (without affecting drawing speed).


It seems that GR already uses Round join now, Is it right? @jheinen

**Comment by jheinen** [comment] 2021-05-30 15:05
The problem is fixed in GR.jl 0.57.5 (with GR run-time 0.57.3).

**Closed by jheinen** 2021-05-30 15:05 UTC
