### ISSUE TITLE
GR segfaults for Plots.jl contour plots

### ISSUE THREAD

**Issue by sethaxen** [jheinen/GR.jl#457] opened 2022-06-04 01:26 UTC
GR_jll v0.64.3 seems to have introduced a bug that causes GR to segfault on contour plots with certain axes. Here's a minimal working example:

```julia
pkg> add Plots

pkg> st -m GR_jll
      Status `/tmp/jl_iLIcaf/Manifest.toml`
  [d2c73de3] GR_jll v0.64.3+0

julia> using Plots

julia> foo(x, y) = exp(-(x^2 + y^2) / 2)
foo (generic function with 1 method)

julia> contour(-3.5:0.05:3.5, -3.5:0.05:3.5, foo) # fine

julia> contour(-3.5:0.05:3.5, -3.5:0.05:7, foo) # segfaults

signal (11): Segmentation fault
in expression starting at none:0
str_ftoa at /home/sethaxen/.julia/artifacts/534ab5a2b484a390ae357f2d17ebb0473e160a9b/lib/libGR.so (unknown line)
gr_ftoa at /home/sethaxen/.julia/artifacts/534ab5a2b484a390ae357f2d17ebb0473e160a9b/lib/libGR.so (unknown line)
gr_axeslbl at /home/sethaxen/.julia/artifacts/534ab5a2b484a390ae357f2d17ebb0473e160a9b/lib/libGR.so (unknown line)
axes2d at /home/sethaxen/.julia/packages/GR/DratL/src/GR.jl:2374 [inlined]
axes at /home/sethaxen/.julia/packages/GR/DratL/src/GR.jl:2380
unknown function (ip: 0x7f3a7b746cd6)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
gr_draw_colorbar at /home/sethaxen/.julia/packages/Plots/1KWPG/src/backends/gr.jl:577
gr_display at /home/sethaxen/.julia/packages/Plots/1KWPG/src/backends/gr.jl:1010
unknown function (ip: 0x7f3a7b712a6b)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
gr_display at /home/sethaxen/.julia/packages/Plots/1KWPG/src/backends/gr.jl:670
gr_display at /home/sethaxen/.julia/packages/Plots/1KWPG/src/backends/gr.jl:636 [inlined]
_display at /home/sethaxen/.julia/packages/Plots/1KWPG/src/backends/gr.jl:2199
display at /home/sethaxen/.julia/packages/Plots/1KWPG/src/output.jl:146
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
display at ./multimedia.jl:328
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:757
#invokelatest#2 at ./essentials.jl:716 [inlined]
invokelatest at ./essentials.jl:714 [inlined]
print_response at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:293
#45 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:277
jfptr_YY.45_47416.clone_1 at /home/sethaxen/.julia/juliaup/julia-1.7.3+0~x64/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
with_repl_linfo at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:510
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
print_response at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:275
do_respond at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:846
jfptr_do_respond_47228.clone_1 at /home/sethaxen/.julia/juliaup/julia-1.7.3+0~x64/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
#82 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:1174
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
jl_f__call_latest at /buildworker/worker/package_linux64/build/src/builtins.c:757
#invokelatest#2 at ./essentials.jl:716 [inlined]
invokelatest at ./essentials.jl:714 [inlined]
#25 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:1466
jfptr_YY.25_47507.clone_1 at /home/sethaxen/.julia/juliaup/julia-1.7.3+0~x64/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
prompt! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2586
run_interface at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/LineEdit.jl:2488
jfptr_run_interface_47761.clone_1 at /home/sethaxen/.julia/juliaup/julia-1.7.3+0~x64/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
run_frontend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.7/REPL/src/REPL.jl:1232
#49 at ./task.jl:429
jfptr_YY.49_47185.clone_1 at /home/sethaxen/.julia/juliaup/julia-1.7.3+0~x64/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2247 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2429
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1788 [inlined]
start_task at /buildworker/worker/package_linux64/build/src/task.c:877
Allocations: 40182907 (Pool: 40165032; Big: 17875); GC: 43
```

If we pin GR_jll to an earlier version, then the segfault doesn't happen:

```julia
pkg> add Plots, GR_jll@v0.64.2

julia> using Plots

julia> foo(x, y) = exp(-(x^2 + y^2) / 2)
foo (generic function with 1 method)

julia> contour(-3.5:0.05:3.5, -3.5:0.05:3.5, foo) # fine

julia> contour(-3.5:0.05:3.5, -3.5:0.05:7, foo) # fine
```

**Comment by jheinen** [comment] 2022-06-04 06:21
Thanks for the hint. I can reproduce the problem and we will fix it ASAP.

**Comment by jheinen** [comment] 2022-06-04 06:26
The problem is already fixed in the development tree. We will tag a new version next week.

**Comment by sethaxen** [comment] 2022-06-04 09:26
Thanks!

**Comment by JeffFessler** [comment] 2022-06-04 14:55
I also got segfaults in my Documenter builds that seemed to be GR related.
I don't have a MWE so hopefully the fix covers my case too :)
https://github.com/JeffFessler/SPECTrecon.jl/runs/6738110042?check_suite_focus=true
Thanks!

**Comment by josephcbradley** [comment] 2022-06-06 15:41
To add to this - I see a similar segfault plotting heatmaps:

```
using LinearAlgebra, Plots
M = Symmetric(rand(10, 10))
V = eigvecs(M)
heatmap(V) #works fine 
Y = V * V'
heatmap(Y) #faults
```

Not sure if it's related - also on GR_jll v0.64.3+0.

**Comment by JeffFessler** [comment] 2022-06-07 01:28
> I see a similar segfault

That code worked fine for me with GR 0.64.2 but when I did an update to GR 0.62.3 it segfaulted for me too.  (Both Julia 1.7.3 and 1.8.0-rc1 on Intel Mac.)
The the matrix `Y` has tiny values in it, suggesting a colorbar issue.
Here is a an even simpler way to reproduce the issue:

```julia
using Plots
X = ones(2,2)
heatmap(X) # works fine
X[1] = 1e-16
heatmap(X, colorbar=:none) # works fine
heatmap(X) # segfault with GR.jl 0.64.3
```

**Comment by JeffFessler** [comment] 2022-06-10 13:09
This works fine with 0.64.4 so issue can be closed - thanks!

**Closed** 2022-06-10 13:45 UTC
