### ISSUE TITLE
Jupyter Notebook - unlink error

### ISSUE THREAD

**Issue by MLackner** [jheinen/GR.jl#82] opened 2017-11-10 22:21 UTC
Hi!
I'm getting the following error in Jupyter Notebook:
```julia
using GR
histogram(randn(10000))
```
```julia
unlink: resource busy or locked (EBUSY)

Stacktrace:
 [1] uv_error at .\libuv.jl:68 [inlined]
 [2] unlink(::String) at .\file.jl:500
 [3] #rm#7(::Bool, ::Bool, ::Function, ::String) at .\file.jl:145
 [4] rm(::String) at .\file.jl:137
 [5] show() at C:\Users\Michael\.julia\v0.6\GR\src\GR.jl:3083
 [6] plot_data(::Bool) at C:\Users\Michael\.julia\v0.6\GR\src\jlgr.jl:892
 [7] #histogram#33(::Array{Any,1}, ::Function, ::Array{Float64,1}) at C:\Users\Michael\.julia\v0.6\GR\src\jlgr.jl:1112
 [8] #histogram#13 at C:\Users\Michael\.julia\v0.6\GR\src\GR.jl:2929 [inlined]
 [9] histogram(::Array{Float64,1}) at C:\Users\Michael\.julia\v0.6\GR\src\GR.jl:2929
 [10] include_string(::String, ::String) at .\loading.jl:522
```

Running Julia v0.6.1 on Windows 10 64bit
Jupyter Notebook Server version: 5.2.1

The above code works in the REPL without a problem

**Comment by jheinen** [comment] 2017-11-11 09:15
I can reproduce the problem - I'll see how we can fix it.

**Comment by jheinen** [comment] 2017-11-11 10:38
The problem is fixed in GR master (https://github.com/jheinen/GR.jl/commit/b59c4862f736eeba6ee5297653115498b5ea7568)

**Comment by MLackner** [comment] 2017-11-12 14:54
Thanks!
Works for me now.

**Closed** 2018-05-16 05:26 UTC
