### ISSUE TITLE
Can't fit world coordinates to the active workstation

### ISSUE THREAD

**Issue by tmptrash** [jheinen/GR.jl#26] opened 2016-07-05 13:24 UTC
Hi, again :)

This second issue is a part of more global problem: drawing a pixel in a window with special width and height. As i told before, i use this code for setting window size:

```julia
mwidth, mheight, width, height = GR.inqdspsize()
w = 400
h = 300
if w >= h
    ratio = float(h) / w
    msize = mwidth * w / width
    GR.setwsviewport(0, msize, 0, msize * ratio)
    GR.setwswindow(0, 1, 0, ratio)
else
    ratio = float(w) / h
    msize = mheight * h / height
    GR.setwsviewport(0, msize * ratio, 0, msize)
    GR.setwswindow(0, ratio, 0, 1)
end
```
But i can't set world coordinates to the same size, like window has. Let's say, i need a window 400x300px. And if i call for example, fillrect(1, 400, 1, 300) it will not has maximum size. I found, that on my resolution i have to add 7.5 to x and -10 to y to fix the problem. But why?

See full code version here:
```julia
mwidth, mheight, width, height = GR.inqdspsize()
w = 400
h = 300
if w >= h
    ratio = float(h) / w
    msize = mwidth * w / width
    GR.setwsviewport(0, msize, 0, msize * ratio)
    GR.setwswindow(0, 1, 0, ratio)
else
    ratio = float(w) / h
    msize = mheight * h / height
    GR.setwsviewport(0, msize * ratio, 0, msize)
    GR.setwswindow(0, ratio, 0, 1)
end

setviewport(0, 1, 0, ratio)
#setwindow(1, w + 7.5, -10, h) # this line fixes size problem on 1280x720 resolution
setwindow(1, w, 1, h)
#...
drawrect(1, w, 1, h) # draws incorrect rect
```

See [this](https://www.dropbox.com/s/n4dmcogbcy09mh2/fit.png?dl=0) screenshot for details. May be i doing something wrong?

**Comment by jheinen** [comment] 2016-07-05 14:19
I can't reproduce the problem. If I run your script and obtain the window information (using xwininfo), I get  the correct result:

> xwininfo 
> 
> xwininfo: Please select the window about which you
>           would like information by clicking the
>           mouse in that window.
> 
> xwininfo: Window id: 0x600001 "GKS 5"
> 
>   Absolute upper-left X:  4
>   Absolute upper-left Y:  1136
>   Relative upper-left X:  0
>   Relative upper-left Y:  22
>   Width: 400
>   Height: 300
>   Depth: 24
>   Visual: 0x22
>   Visual Class: TrueColor
>   Border width: 0
>   Class: InputOutput
>   Colormap: 0x21 (installed)
>   Bit Gravity State: ForgetGravity
>   Window Gravity State: NorthWestGravity
>   Backing Store State: NotUseful
>   Save Under State: no
>   Map State: IsViewable
>   Override Redirect State: no
>   Corners:  +4+1136  -2156+1136  -2156--18  +4--18
>   -geometry 400x300+4--18
> 

So, my question is: What is the output of ``xdpyinfo`` on your display? Are the dimension for your default screen correct? That's what I see for my display:

> screen #0:
>   dimensions:    2560x1418 pixels (677x375 millimeters)

**Comment by tmptrash** [comment] 2016-07-05 14:50
Full code is [here](https://github.com/tmptrash/jevo/blob/master/tmp/gltmp.jl). Screenshots are
[here](https://www.dropbox.com/s/wov61w7990u0838/600h.png?dl=0) and [here](https://www.dropbox.com/s/rim29u5h80ibj4d/800w.png?dl=0). I also use special setting for windows fonts. Their size is 150%. I use Windows 8.1.

**Comment by jheinen** [comment] 2016-07-05 15:26
Same issue than #25. Has been fixed with https://github.com/jheinen/gr/commit/0adb216927851b818f756e3efd06606941ce13a6

**Comment by tmptrash** [comment] 2016-07-06 06:23
It looks like i still need to add some coefficients to fit the world coordinates to window area. Look, [this](https://www.dropbox.com/s/ahtsndyvsogyp7z/size.png?dl=0) is output of `setwindow(1, w, 1, h)` and `drawrect(1, w, 1, h)`... The rect is bigger then the window. If i change setwindow to: `setwindow(1, w + 9.5, -12.7, h)` it start working. Full code is [here](https://github.com/tmptrash/jevo/blob/master/tmp/gltmp.jl).

**Comment by tmptrash** [comment] 2016-07-06 23:13
If these values (9.5 and -12.7) are window decorators, then you may close the issue ;)

**Comment by jheinen** [comment] 2016-07-07 06:04
The offsets (9.5, -12.7) are **not** necessary on Windows 10 and can be omitted - they should correctly be handled (internally) in GR driver. Do you still have problems using Windows 8.x?

The following code snippet does exactly what expected:

```
using GR

mwidth, mheight, width, height = GR.inqdspsize()

while true
    clearws()

    w = 400 + round(Int, rand() * 200)
    h = 400 + round(Int, rand() * 200)
    if w >= h
        ratio = float(h) / w
        msize = mwidth * w / width
        GR.setwsviewport(0, msize, 0, msize * ratio)
        GR.setwswindow(0, 1, 0, ratio)
        setviewport(0, 1, 0, ratio)
    else
        ratio = float(w) / h
        msize = mheight * h / height
        GR.setwsviewport(0, msize * ratio, 0, msize)
        GR.setwswindow(0, ratio, 0, 1)
        setviewport(0, ratio, 0, 1)
    end
    
    setwindow(1, w, 1, h)
    
    drawrect(1, w, 1, h)
    polyline([1,w],[1,h])
    polyline([1,w],[h,1])
    text(0.05, 0.05, "$w x $h")

    updatews()
    sleep(0.5)
end

```

Isn't it working on your Windows system?

**Comment by tmptrash** [comment] 2016-07-07 08:53
No. This snippet produces alot of windows with different sizes, but all of them have incorrect widths and heights of the rect. See [this](https://www.dropbox.com/s/9lgckwta4unb85i/size.png?dl=0) screenshot for details.

**Comment by jheinen** [comment] 2016-07-07 09:42
Are you really using the latest GR binaries?

````
julia> stat(joinpath(Pkg.dir("GR"),"deps","gr","libgks.dll"))
StatStruct(mode=100666, size=378880)
````

The size of libgks.dll should be **378880** (creation date is Jul  6 15:42). If you have an older version, please re-install GR:

```
Pkg.rm("GR")
Pkg.add("GR")
Pkg.checkout("GR")
```

I tagged a new version this morning (v0.13.0). Once it is merged, you can omit the checkout.

If the problem still exists, I have to find a Windows 8.x machine to reproduce the behaviour ...

**Comment by tmptrash** [comment] 2016-07-07 12:29
Checking again...

**Comment by tmptrash** [comment] 2016-07-07 12:59
Hmmm. I have strange error:
```
julia> Pkg.add("GR")
INFO: Installing GR v0.12.0
fatal: Not a git repository (or any of the parent directories): .git
ERROR: failed process: Process(setenv(`git rev-parse --git-dir`; dir="C:\\Users\\User\\.julia\\v0.4\\GR"), ProcessExited(128)) [128]
 in pipeline_error at process.jl:555
 in sync_end at task.jl:413
 [inlined code] from task.jl:422
 in add at pkg/entry.jl:64
 in add at pkg/entry.jl:73
 in anonymous at pkg/dir.jl:31
 in cd at file.jl:32
 in cd at pkg/dir.jl:31
 in add at pkg.jl:23
```

**Comment by tmptrash** [comment] 2016-07-07 13:05
By the way. During remove i see this:
```
julia> Pkg.rm("GR")
INFO: Removing GR (unregistered)
```
Why it's unregistered?

**Comment by jheinen** [comment] 2016-07-07 13:06
Huh? You could manually remove ``C:\Users\Users\.julia\v0.4\GR`` and retry with ``Pkg.update(); Pkg.add("GR")``

**Comment by tmptrash** [comment] 2016-07-07 13:23
Okay! I have fixed all the problems. So, it looks like height is okay, but the width is still incorrect. See my [screenshot](https://www.dropbox.com/s/b8n9823l4w6v6il/size.png?dl=0).

**Comment by jheinen** [comment] 2016-07-07 14:34
I increased the width/height for the Windows GDI display by 1px and patched the run-time libraries. Please install the patched binaries:
```
julia> rm(joinpath(Pkg.dir("GR"),"downloads"),recursive=true)
julia> Pkg.build("GR")
```

**Comment by tmptrash** [comment] 2016-07-07 16:54
Great job! It works fine. Only height now a little bit smaller then a window :-D I think, this is because you have added 1 pixel for both width and height, but only width was incorrect. Anyway, you may leave like this. For my project it's not so important. So, thanks again.

P.S. See, how i [use](https://raw.githubusercontent.com/tmptrash/jevo/master/store/stat/2016-07-06%2013.57/screenshot.png) it on my small evolutionary programming pat project ;)

**Closed** 2016-07-07 20:03 UTC
